# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 649)
        MainWindow.setStyleSheet("background-color: rgb(86, 86, 139);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.number = QtWidgets.QLineEdit(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(160, 20, 271, 51))
        self.number.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"placeholder=\'numbers1\'")
        self.number.setObjectName("number")
        self.number2 = QtWidgets.QLineEdit(self.centralwidget)
        self.number2.setGeometry(QtCore.QRect(160, 110, 271, 51))
        self.number2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.number2.setObjectName("number2")
        self.text = QtWidgets.QLineEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(30, 30, 113, 22))
        self.text.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.text.setObjectName("text")
        self.text2 = QtWidgets.QLineEdit(self.centralwidget)
        self.text2.setGeometry(QtCore.QRect(30, 120, 113, 22))
        self.text2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.text2.setObjectName("text2")
        self.number2_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.number2_2.setGeometry(QtCore.QRect(100, 420, 261, 61))
        self.number2_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.number2_2.setObjectName("number2_2")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(90, 250, 41, 28))
        self.plus.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(310, 250, 41, 28))
        self.minus.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.minus.setObjectName("minus")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "numbers"))
        self.text2.setText(_translate("MainWindow", "numbers_2"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
